In [20]:
import sys
print(sys.executable)

d:\KrishNaik_Course\DeepLearning\ANN\venv\python.exe

In [21]:
import tensorflow as tf
print(tf.__version__)

2.15.0

In [22]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

import pickle

In [23]:
import pandas as pd

df = pd.read_csv("Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [24]:
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [25]:
from sklearn.preprocessing import LabelEncoder

label_encoder_gender = LabelEncoder()

df['Gender'] = label_encoder_gender.fit_transform(df['Gender'])

In [26]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [27]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

one_hot_encoder_geo = OneHotEncoder()

ct = ColumnTransformer(
    transformers=[
        ('onehot', one_hot_encoder_geo, ['Geography'])
    ],
    remainder='passthrough'
)

df = ct.fit_transform(df)

In [28]:
df.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [29]:
geo_encoder = OneHotEncoder()
geo_encoded = geo_encoder.fit_transform(df[['Geography']]).toarray()

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [31]:
df = ct.fit_transform(df)

ValueError: Specifying the columns using strings is only supported for dataframes.

In [32]:
df.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [33]:
import pandas as pd

df = pd.read_csv("Churn_Modelling.csv")

In [34]:
df.drop(['RowNumber','CustomerId','Surname'], axis=1, inplace=True)

In [35]:
from sklearn.preprocessing import LabelEncoder

label_encoder_gender = LabelEncoder()

df['Gender'] = label_encoder_gender.fit_transform(df['Gender'])

In [36]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [37]:
from sklearn.preprocessing import OneHotEncoder

geo_encoder = OneHotEncoder(sparse_output=False)

geo_encoded = geo_encoder.fit_transform(df[['Geography']])

In [38]:
geo_encoded_df = pd.DataFrame(
    geo_encoded,
    columns=geo_encoder.get_feature_names_out(['Geography'])
)

In [39]:
df = pd.concat(
    [df.drop('Geography', axis=1), geo_encoded_df],
    axis=1
)

In [40]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [42]:
type(df)

pandas.DataFrame

In [43]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [45]:
import pickle

pickle.dump(label_encoder_gender,
            open("label_encoder_gender.pkl","wb"))

pickle.dump(one_hot_encoder_geo,
            open("onehot_encoder_geo.pkl","wb"))

In [46]:
X = df.drop('Exited', axis=1)
y = df['Exited']

In [47]:
print(X.head())

   CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1
1          608       0   41       1   83807.86              1          0
2          502       0   42       8  159660.80              3          1
3          699       0   39       1       0.00              2          0
4          850       0   43       2  125510.82              1          1

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1        101348.88               1.0                0.0
1               1        112542.58               0.0                0.0
2               0        113931.57               1.0                0.0
3               0         93826.63               1.0                0.0
4               1         79084.10               0.0                0.0

   Geography_Spain
0              0.0
1              1.0
2              0.0
3              0.0
4              1.0

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [49]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [50]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 12)
(2000, 12)
(8000,)
(2000,)

In [51]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [52]:
import pickle

pickle.dump(scaler,
            open("scaler.pkl","wb"))

In [53]:
print(X_train[:5])

[[ 0.35649971  0.91324755 -0.6557859   0.34567966 -1.21847056  0.80843615
   0.64920267  0.97481699  1.36766974  1.00150113 -0.57946723 -0.57638802]
 [-0.20389777  0.91324755  0.29493847 -0.3483691   0.69683765  0.80843615
   0.64920267  0.97481699  1.6612541  -0.99850112  1.72572313 -0.57638802]
 [-0.96147213  0.91324755 -1.41636539 -0.69539349  0.61862909 -0.91668767
   0.64920267 -1.02583358 -0.25280688 -0.99850112 -0.57946723  1.73494238]
 [-0.94071667 -1.09499335 -1.13114808  1.38675281  0.95321202 -0.91668767
   0.64920267 -1.02583358  0.91539272  1.00150113 -0.57946723 -0.57638802]
 [-1.39733684  0.91324755  1.62595257  1.38675281  1.05744869 -0.91668767
  -1.54035103 -1.02583358 -1.05960019  1.00150113 -0.57946723 -0.57638802]]

In [54]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [56]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import TensorBoard, EarlyStopping
import datetime

In [57]:
model = Sequential()

WARNING:tensorflow:From d:\KrishNaik_Course\DeepLearning\ANN\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [58]:
model.add(Dense(units=64, activation='relu', input_shape=(X_train.shape[1],)))

In [59]:
# Second Hidden Layer
model.add(Dense(units=32,
                activation='relu'))

# Output Layer
model.add(Dense(units=1,
                activation='sigmoid'))

In [60]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [61]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

WARNING:tensorflow:From d:\KrishNaik_Course\DeepLearning\ANN\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [62]:
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

In [63]:
tensorboard_callback = TensorBoard(
    log_dir=log_dir,
    histogram_freq=1
)

In [64]:
early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

In [ ]:
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[tensorboard_callback, early_stopping]
)

In [65]:
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[tensorboard_callback, early_stopping]
)

Epoch 1/100
WARNING:tensorflow:From d:\KrishNaik_Course\DeepLearning\ANN\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\KrishNaik_Course\DeepLearning\ANN\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 5s 7ms/step - loss: 0.4671 - accuracy: 0.7914 - val_loss: 0.3972 - val_accuracy: 0.8275
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3847 - accuracy: 0.8441 - val_loss: 0.3587 - val_accuracy: 0.8505
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3553 - accuracy: 0.8541 - val_loss: 0.3443 - val_accuracy: 0.8600
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3467 - accuracy: 0.8579 - val_loss: 0.3464 - val_accuracy: 0.8550
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3432 - accuracy: 0.8576 - val_loss: 0.3410 - val_accuracy: 0.8595
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3374 - accuracy: 0.8594 - val_loss: 0.3456 - val_accuracy: 0.8575
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3353 - accuracy: 0.8612 - val_loss: 0.3423 - val_accuracy: 0.8600
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3316 - accuracy: 0.8646 - val_loss: 0.3390 - val_accuracy: 0.8620
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3309 - accuracy: 0.8612 - val_loss: 0.3449 - val_accuracy: 0.8595
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3278 - accuracy: 0.8645 - val_loss: 0.3394 - val_accuracy: 0.8630
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3269 - accuracy: 0.8659 - val_loss: 0.3381 - val_accuracy: 0.8625
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3241 - accuracy: 0.8662 - val_loss: 0.3411 - val_accuracy: 0.8645
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3224 - accuracy: 0.8674 - val_loss: 0.3404 - val_accuracy: 0.8580
Epoch 14/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3211 - accuracy: 0.8666 - val_loss: 0.3460 - val_accuracy: 0.8580
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3184 - accuracy: 0.8674 - val_loss: 0.3418 - val_accuracy: 0.8595
Epoch 16/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3167 - accuracy: 0.8687 - val_loss: 0.3377 - val_accuracy: 0.8620
Epoch 17/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3155 - accuracy: 0.8681 - val_loss: 0.3405 - val_accuracy: 0.8610
Epoch 18/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3157 - accuracy: 0.8671 - val_loss: 0.3429 - val_accuracy: 0.8645
Epoch 19/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3136 - accuracy: 0.8710 - val_loss: 0.3381 - val_accuracy: 0.8620
Epoch 20/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3108 - accuracy: 0.8685 - val_loss: 0.3486 - val_accuracy: 0.8635
Epoch 21/100
250/250 [==============================] - 3s 10ms/step - loss: 0.3099 - accuracy: 0.8723 - val_loss: 0.3429 - val_accuracy: 0.8625
Epoch 22/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3088 - accuracy: 0.8701 - val_loss: 0.3412 - val_accuracy: 0.8625
Epoch 23/100
250/250 [==============================] - 3s 10ms/step - loss: 0.3087 - accuracy: 0.8704 - val_loss: 0.3443 - val_accuracy: 0.8600
Epoch 24/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3066 - accuracy: 0.8729 - val_loss: 0.3396 - val_accuracy: 0.8605
Epoch 25/100
250/250 [==============================] - 3s 10ms/step - loss: 0.3058 - accuracy: 0.8714 - val_loss: 0.3435 - val_accuracy: 0.8655
Epoch 26/100
250/250 [==============================] - 2s 10ms/step - loss: 0.3044 - accuracy: 0.8735 - val_loss: 0.3438 - val_accuracy: 0.8630

In [66]:

test_loss, test_accuracy = model.evaluate(X_test, y_test)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

63/63 [==============================] - 0s 2ms/step - loss: 0.3377 - accuracy: 0.8620
Test Loss: 0.3376920223236084
Test Accuracy: 0.8619999885559082

In [67]:
model.save('churn_model.h5')

d:\KrishNaik_Course\DeepLearning\ANN\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [68]:
%load_ext tensorboard

In [69]:
%tensorboard --logdir logs/fit

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\KrishNaik_Course\DeepLearning\ANN\venv\Scripts\tensorboard.exe\__main__.py", line 2, in <module>
  File "D:\KrishNaik_Course\DeepLearning\ANN\venv\Lib\site-packages\tensorboard\main.py", line 27, in <module>
    from tensorboard import default
  File "D:\KrishNaik_Course\DeepLearning\ANN\venv\Lib\site-packages\tensorboard\default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [70]:
pip install setuptools

Requirement already satisfied: setuptools in d:\KrishNaik_Course\DeepLearning\ANN\venv\Lib\site-packages (83.0.0)
Note: you may need to restart the kernel to use updated packages.

In [72]:
python -c "import pkg_resources; print(pkg_resources.__file__)"

SyntaxError: invalid syntax (1915112788.py, line 1)

In [71]:
%load_ext tensorboard
%tensorboard --logdir logs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\KrishNaik_Course\DeepLearning\ANN\venv\Scripts\tensorboard.exe\__main__.py", line 2, in <module>
  File "D:\KrishNaik_Course\DeepLearning\ANN\venv\Lib\site-packages\tensorboard\main.py", line 27, in <module>
    from tensorboard import default
  File "D:\KrishNaik_Course\DeepLearning\ANN\venv\Lib\site-packages\tensorboard\default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [73]:
pip install setuptools==69.5.1

Collecting setuptools==69.5.1
  Downloading setuptools-69.5.1-py3-none-any.whl.metadata (6.2 kB)
Downloading setuptools-69.5.1-py3-none-any.whl (894 kB)
   ---------------------------------------- 0.0/894.6 kB ? eta -:--:--
   ---------------------------------------- 894.6/894.6 kB 5.8 MB/s  0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 83.0.0
    Uninstalling setuptools-83.0.0:
      Successfully uninstalled setuptools-83.0.0
Successfully installed setuptools-69.5.1
Note: you may need to restart the kernel to use updated packages.

In [76]:
import pkg_resources

print("pkg_resources imported successfully")

pkg_resources imported successfully

C:\Users\chandra sekhar\AppData\Local\Temp\ipykernel_24896\2029937887.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources

In [77]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [79]:
import os

for root, dirs, files in os.walk("logs"):
    print(root)
    for f in files:
        print("   ", f)

logs
logs\fit
logs\fit\20260807-093901
logs\fit\20260807-093901\train
    events.out.tfevents.1786076356.DESKTOP-6K4M1V5.24896.0.v2
logs\fit\20260807-093901\validation
    events.out.tfevents.1786076361.DESKTOP-6K4M1V5.24896.1.v2

In [1]:
print(log_dir)

NameError: name 'log_dir' is not defined

In [3]:
from sklearn.preprocessing import OneHotEncoder

In [5]:
geo_encoder = OneHotEncoder()

geo_encoded = geo_encoder.fit_transform(
    df[['Geography']]
).toarray()

NameError: name 'df' is not defined

In [6]:
import pandas as pd

df = pd.read_csv("Churn_Modelling.csv")

In [7]:
from sklearn.preprocessing import OneHotEncoder

geo_encoder = OneHotEncoder()

geo_encoded = geo_encoder.fit_transform(
    df[['Geography']]
).toarray()

In [8]:
print(geo_encoder.categories_)

[array(['France', 'Germany', 'Spain'], dtype=object)]

In [9]:
import pickle

pickle.dump(
    geo_encoder,
    open("onehot_encoder_geo.pkl", "wb")
)